// ============================================
// 视频滤镜效果 - 30+种滤镜
// ============================================

export interface FilterPreset {
  id: string;
  name: string;
  nameCn: string;
  category: string;
  icon: string;
  params: Record<string, number | string>;
  description?: string;
}

// 滤镜预设库
export const FILTER_PRESETS: FilterPreset[] = [
  // ========== 基础调色 ==========
  {
    id: 'brightness-up',
    name: 'Brightness Up',
    nameCn: '提亮',
    category: 'basic',
    icon: '☀️',
    params: { brightness: 0.15 },
    description: '整体提亮画面',
  },
  {
    id: 'brightness-down',
    name: 'Brightness Down',
    nameCn: '变暗',
    category: 'basic',
    icon: '🌙',
    params: { brightness: -0.15 },
    description: '整体压暗画面',
  },
  {
    id: 'contrast-up',
    name: 'High Contrast',
    nameCn: '高对比度',
    category: 'basic',
    icon: '🔳',
    params: { contrast: 1.3 },
    description: '增强对比度',
  },
  {
    id: 'contrast-down',
    name: 'Low Contrast',
    nameCn: '低对比度',
    category: 'basic',
    icon: '🔲',
    params: { contrast: 0.8 },
    description: '降低对比度，柔和画面',
  },
  {
    id: 'saturation-up',
    name: 'Vivid',
    nameCn: '鲜艳',
    category: 'basic',
    icon: '🌈',
    params: { saturation: 1.4 },
    description: '增强色彩饱和度',
  },
  {
    id: 'saturation-down',
    name: 'Muted',
    nameCn: '柔和',
    category: 'basic',
    icon: '🌫️',
    params: { saturation: 0.7 },
    description: '降低色彩饱和度',
  },

  // ========== 色彩风格 ==========
  {
    id: 'warm',
    name: 'Warm',
    nameCn: '暖色调',
    category: 'color',
    icon: '🔥',
    params: { temperature: 30 },
    description: '温暖色调',
  },
  {
    id: 'cool',
    name: 'Cool',
    nameCn: '冷色调',
    category: 'color',
    icon: '❄️',
    params: { temperature: -30 },
    description: '清冷色调',
  },
  {
    id: 'vintage',
    name: 'Vintage',
    nameCn: '复古',
    category: 'color',
    icon: '📷',
    params: { sepia: 0.4, contrast: 0.95, saturation: 0.85 },
    description: '复古怀旧风格',
  },
  {
    id: 'sepia',
    name: 'Sepia',
    nameCn: '怀旧',
    category: 'color',
    icon: '📜',
    params: { sepia: 0.8 },
    description: '经典怀旧褐色调',
  },
  {
    id: 'black-white',
    name: 'Black & White',
    nameCn: '黑白',
    category: 'color',
    icon: '⬛',
    params: { saturation: 0 },
    description: '黑白效果',
  },
  {
    id: 'cinematic',
    name: 'Cinematic',
    nameCn: '电影感',
    category: 'color',
    icon: '🎬',
    params: { contrast: 1.1, saturation: 0.9, temperature: -10, vignette: 0.3 },
    description: '电影风格调色',
  },
  {
    id: 'teal-orange',
    name: 'Teal & Orange',
    nameCn: '青橙',
    category: 'color',
    icon: '🧡',
    params: { shadows: 'teal', highlights: 'orange', saturation: 1.1 },
    description: '好莱坞经典青橙调色',
  },
  {
    id: 'cyberpunk',
    name: 'Cyberpunk',
    nameCn: '赛博朋克',
    category: 'color',
    icon: '🤖',
    params: { saturation: 1.3, temperature: -20, hue: 10, contrast: 1.15 },
    description: '赛博朋克风格',
  },
  {
    id: 'sunset',
    name: 'Sunset',
    nameCn: '日落',
    category: 'color',
    icon: '🌅',
    params: { temperature: 40, saturation: 1.2, contrast: 1.05 },
    description: '日落暖色调',
  },
  {
    id: 'forest',
    name: 'Forest',
    nameCn: '森林',
    category: 'color',
    icon: '🌲',
    params: { temperature: -15, saturation: 1.15, hue: -5 },
    description: '自然森林色调',
  },
  {
    id: 'ocean',
    name: 'Ocean',
    nameCn: '海洋',
    category: 'color',
    icon: '🌊',
    params: { temperature: -25, saturation: 1.1, contrast: 1.1 },
    description: '清新海洋蓝调',
  },

  // ========== 特效滤镜 ==========
  {
    id: 'vhs',
    name: 'VHS',
    nameCn: '录像带',
    category: 'effect',
    icon: '📼',
    params: { noise: 0.15, rgbShift: 0.5, scanlines: 0.3, saturation: 0.9 },
    description: '复古录像带效果',
  },
  {
    id: 'film-grain',
    name: 'Film Grain',
    nameCn: '胶片颗粒',
    category: 'effect',
    icon: '🎞️',
    params: { noise: 0.2, contrast: 1.05 },
    description: '胶片颗粒质感',
  },
  {
    id: 'dreamy',
    name: 'Dreamy',
    nameCn: '梦幻',
    category: 'effect',
    icon: '✨',
    params: { blur: 0.3, brightness: 0.1, saturation: 1.2 },
    description: '梦幻柔光效果',
  },
  {
    id: 'glitch',
    name: 'Glitch',
    nameCn: '故障',
    category: 'effect',
    icon: '⚡',
    params: { rgbShift: 1.5, noise: 0.1, contrast: 1.1 },
    description: '数字故障效果',
  },
  {
    id: 'pixelate',
    name: 'Pixelate',
    nameCn: '像素化',
    category: 'effect',
    icon: '🎮',
    params: { pixelSize: 8 },
    description: '像素化效果',
  },
  {
    id: 'halftone',
    name: 'Halftone',
    nameCn: '半色调',
    category: 'effect',
    icon: '📰',
    params: { halftone: 4 },
    description: '印刷品半色调效果',
  },
  {
    id: 'posterize',
    name: 'Posterize',
    nameCn: '海报化',
    category: 'effect',
    icon: '🎨',
    params: { posterize: 4 },
    description: '海报风格色彩分离',
  },
  {
    id: 'emboss',
    name: 'Emboss',
    nameCn: '浮雕',
    category: 'effect',
    icon: '🗿',
    params: { emboss: 1 },
    description: '浮雕效果',
  },
  {
    id: 'sketch',
    name: 'Sketch',
    nameCn: '素描',
    category: 'effect',
    icon: '✏️',
    params: { sketch: 1, saturation: 0 },
    description: '素描画效果',
  },
  {
    id: 'oil-paint',
    name: 'Oil Paint',
    nameCn: '油画',
    category: 'effect',
    icon: '🖼️',
    params: { oilPaint: 1 },
    description: '油画风格',
  },
  {
    id: 'cartoon',
    name: 'Cartoon',
    nameCn: '卡通',
    category: 'effect',
    icon: '🎭',
    params: { posterize: 6, edge: 0.5, saturation: 1.2 },
    description: '卡通动画风格',
  },
  {
    id: 'neon',
    name: 'Neon',
    nameCn: '霓虹',
    category: 'effect',
    icon: '💡',
    params: { saturation: 1.5, contrast: 1.3, brightness: 0.1 },
    description: '霓虹灯效果',
  },

  // ========== 边框效果 ==========
  {
    id: 'vignette',
    name: 'Vignette',
    nameCn: '暗角',
    category: 'frame',
    icon: '⭕',
    params: { vignette: 0.5 },
    description: '经典暗角效果',
  },
  {
    id: 'vignette-light',
    name: 'Vignette Light',
    nameCn: '亮角',
    category: 'frame',
    icon: '⚪',
    params: { vignette: -0.3 },
    description: '边缘变亮效果',
  },
  {
    id: 'letterbox',
    name: 'Letterbox',
    nameCn: '宽银幕',
    category: 'frame',
    icon: '🎬',
    params: { letterbox: 0.1 },
    description: '电影宽银幕黑边',
  },
  {
    id: 'polaroid',
    name: 'Polaroid',
    nameCn: '拍立得',
    category: 'frame',
    icon: '📸',
    params: { border: 'white', borderRadius: 0.02, sepia: 0.1 },
    description: '拍立得相框效果',
  },

  // ========== 特殊风格 ==========
  {
    id: 'horror',
    name: 'Horror',
    nameCn: '恐怖',
    category: 'style',
    icon: '👻',
    params: { saturation: 0.6, contrast: 1.3, brightness: -0.1, vignette: 0.4 },
    description: '恐怖电影风格',
  },
  {
    id: 'noir',
    name: 'Noir',
    nameCn: '黑色电影',
    category: 'style',
    icon: '🎩',
    params: { saturation: 0, contrast: 1.4, brightness: -0.05, vignette: 0.5 },
    description: '经典黑色电影风格',
  },
  {
    id: 'pop-art',
    name: 'Pop Art',
    nameCn: '波普艺术',
    category: 'style',
    icon: '🎪',
    params: { posterize: 3, saturation: 2, contrast: 1.3 },
    description: '波普艺术风格',
  },
  {
    id: 'bleach-bypass',
    name: 'Bleach Bypass',
    nameCn: '漂白',
    category: 'style',
    icon: '🧪',
    params: { saturation: 0.5, contrast: 1.4, brightness: 0.05 },
    description: '漂白效果，低饱和高对比',
  },
  {
    id: 'cross-process',
    name: 'Cross Process',
    nameCn: '交叉冲印',
    category: 'style',
    icon: '🧬',
    params: { saturation: 1.2, contrast: 1.2, temperature: 15, hue: 5 },
    description: '胶片交叉冲印效果',
  },
  {
    id: 'duotone',
    name: 'Duotone',
    nameCn: '双色调',
    category: 'style',
    icon: '🎭',
    params: { duotone: 'blue-orange', saturation: 1.5 },
    description: '双色调渐变效果',
  },
];

const FILTER_CATEGORIES = [
  { key: 'all', label: '全部', count: FILTER_PRESETS.length },
  { key: 'basic', label: '基础调色', count: FILTER_PRESETS.filter(f => f.category === 'basic').length },
  { key: 'color', label: '色彩风格', count: FILTER_PRESETS.filter(f => f.category === 'color').length },
  { key: 'effect', label: '特效滤镜', count: FILTER_PRESETS.filter(f => f.category === 'effect').length },
  { key: 'frame', label: '边框效果', count: FILTER_PRESETS.filter(f => f.category === 'frame').length },
  { key: 'style', label: '特殊风格', count: FILTER_PRESETS.filter(f => f.category === 'style').length },
];

export { FILTER_CATEGORIES };
